{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Max file size'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int1}&nbsp;MB</p>
</div>
<div class="block">
    <label>{'Max number of files for the upload'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int2}</p>
</div>
<div class="block">
    <label>{'Enable name customisation'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int3}</p>
</div>
<div class="block">
    <label>
        {'Grouping tips (one per line)'|i18n( 'design/standard/class/datatype' )}:
    </label>
    {$class_attribute.data_text_i18n|wash()|nl2br}
</div>